defaults: &defaults
  app:
    admin_email: cantorrodista@gmail.com
    include_for_asset_packager: 0
    url: "http://localhost:3000"
  advertiser:
    logo:
      big_size: "134x199#"
      medium_size: "51x51#"
      small_size: "40x40#"
  banner:    
    image:
      body_medium: "470x470>"
      body: "960x960>"
      sidebar: "1000x200>"
    

development:
  <<: *defaults
  url: 'http://localhost:3000'

test:
  <<: *defaults
  url: 'http://test.host:5555'

production:
  <<: *defaults

