defaults: &defaults
  app:
    admin_email: cantorrodista@gmail.com
    include_for_asset_packager: 0
    url: "http://localhost:3000"
    
  highlight:
    assets:
      styles:
        big_size: "250x250#"
        medium_size: "210x210>"
        small_size: "80x80#"

  advertiser:
    assets:
      styles:
        big_size: "250x250#"
        medium_size: "128x128#"
        small_size: "65x65#"
    logo:
      big_size: "250x250#"
      medium_size: "128x128#"
      small_size: "65x65#"

  banner:    
    image:
      body_medium: "470x470>"
      body: "728x90>"
      sidebar: "180x1000>"
  
  comments:
    activate_moderation: 1
    per_page: 30
  
  ratings:
    unlimited_votes: 0
    login_required: 0
    classes:
      - 'Highlight'

      

development:
  <<: *defaults
  url: 'http://localhost:3000'

test:
  <<: *defaults
  url: 'http://test.host:5555'

production:
  <<: *defaults
  url: 'http://ociociudadreal.cantorrodista.com'
 
