defaults: &defaults
  app:
    admin_email: cantorrodista@gmail.com
    include_for_asset_packager: 0
    url: "http://localhost:3000"
  advertiser:
    logo:
      big_size: "250x250#"
      medium_size: "128x128#"
      small_size: "65x65#"
  banner:    
    image:
      body_medium: "480x480>"
      body: "670x270>"
      sidebar: "180x1000>"
    

development:
  <<: *defaults
  url: 'http://localhost:3000'

test:
  <<: *defaults
  url: 'http://test.host:5555'

production:
  <<: *defaults

