development:
  adapter: mysql
  database: turismo_conquense_dev
  username: root
  password:
  host: localhost
  #socket: /tmp/mysql.sock



test:
  adapter: mysql
  database: turismo_conquense
  username: root
  password:
  host: localhost
  #socket: /tmp/mysql.sock



production:
  adapter: mysql
  database: turismo_conquense
  username: turismo
  password: 23ike8GEo
  host: localhost
  timeout: 5000

