development:
  adapter: mysql
  database: ocr_development
  username: root
  password:
  host: localhost
  #socket: /tmp/mysql.sock



test:
  adapter: mysql
  database: ocr_test
  username: root
  password:
  host: localhost
  #socket: /tmp/mysql.sock



production:
  adapter: mysql
  database: ocr
  username: ocr 
  password: 7yokdjeS34
  host: localhost
  timeout: 5000

