development:
  adapter: mysql
  database: ocr_dev
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock



test:
  adapter: mysql
  database: ocr_test
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock



production:
  adapter: mysql
  database: ocr
  username: root
  password: 
  host: localhost
  timeout: 5000